title: Fabric Docs
description: A collection of documentation and research for the Fabric effort
theme: just-the-docs

url: https://eth-fabric.github.io/
baseurl: /website

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

nav_enabled: true

color_scheme: dark

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  Fabric on GitHub:
    - https://github.com/eth-fabric
  

math: katex

callouts:
  important:
    title: Important
    color: blue
  
favicon_ico: "/assets/images/favicon.ico"